name: rada_prueba
description: "Aplicación de radar de proximidad para Android."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Geolocalización
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  
  # Almacenamiento local
  shared_preferences: ^2.2.3
  
  # Comunicación peer-to-peer (sin servidor) - opcional
  nearby_connections: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true